// GENERATED BY SERVER CODE
var _SETTINGS = {
	'Ad':{
		'Mobile':{
			'Preroll':{
				'Enabled':false,	
				'Duration':5,
				'Width':300,
				'Height':250,			
			},
			'Header':{
				'Enabled':false,	
				'Duration':5,
				'Width':320,
				'Height':50,				
			},	
			'Footer':{
				'Enabled':false,	
				'Duration':5,
				'Width':320,
				'Height':50,				
			},	
			'End':{
				'Enabled':false,	
				'Duration':1,
				'Width':250,
				'Height':250,				
			},								
		},		
	},

	'Language':{
		'Default':'en',		
	},
		
	'Branding':{
		'Splash':{
			'Enabled':false,
		},
		'MainMenu':{
			'Enabled':false,
		}
	},	
	
	'Gamecenter':{
		'Enabled':true,
	},
};
